### ISSUE TITLE
Is environment.lock supposed to be cross-platform?

### ISSUE THREAD

**Issue by jflanaga** [hackalog/cookiecutter-easydata#59]
First, nice set-up. I really like how you've adapted the template. 

I think I'm having an issue with the `environment.lock`. If I understand it correctly, you use it to lock down the versions for a project. That means that future users would use the `environment.lock` rather than the `environment.yml` when they create the virtual environment so that the analysis is reproducible. Is that correct?

If so, I think there might be some issues. First, don't you need the `.yml` extension for conda to be able to recreate the environment from it? Second, and perhaps more important, the method right now includes build information that will cause problems if you move from one platform  to another. I managed to get around that by adding `--no-builds` in the relevant places. However, Conda still add packages that are platform-specific, specifically, my Ubuntu machine adds: 

```
libxcb=1.13
libstdcxx-ng=8.2.0
libgcc-ng=8.2.0
```
And these create a `ResolvePackageNotFound"  error on my Mac. 

Anyways, I wanted to make sure I understood how `environment.lock` was supposed to work before trying to see how I could fix the issue. 

By the way, have you looked at `Poetry` as a means of handling package dependencies?

**Comment by hackalog** [comment]
Hello @jflanaga, and welcome!

`environment.lock` is indeed a work-in-progress, for all the reasons you state. We do go into this a bit ("conda is not really reproducible") when we give the Bus Number tutorial (https://github.com/hackalog/bus_number/). I suspect this is going to boil down to some fixes upstream in conda-env (or elsewhere in the conda toolchain) to truly handle the cross-platform reproducibility issues.

We really *want* a lockfile mechanism to work with `environment.yml` (to both cut down on dependency graph resolution time, and to make things truly reproducible), but, as you point out, `conda-env` yml can be platform specific.

(By the way, I hadn't noticed that the `.yml` extension had become mandatory: https://github.com/conda/conda/issues/8203). While annoying, that is at least something we can work around. Feel free to file an issue for that one!

So right now, `environment.lock` is purely advisory. It gets created whenever environment.yml changes, but we don't yet use it to install or update the environment, because of some of the issues you mention. 

(This isn't entirely pointless. It's **very nice** to know us know one of the downstream dependencies has changed, so if we see a change in behavior, we can go back and lock the old version by adding it to `environment.yml` with an explicit version number.)

We'd love to see if there's a fix, so please, keep us apprised (with comments or PRs) if you have ideas.

**Comment by hackalog** [comment]
Also: No, we haven't looked at Poetry yet, but we're happy to entertain PRs to add support.

**Comment by hackalog** [comment]
Lockfiles are now platform-specific. Thanks for the nudge!
